/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 52
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 16
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_document_token1 = 1,
  anon_sym_MSH = 2,
  anon_sym_PIPE = 3,
  anon_sym_CARET_TILDE_BSLASH_AMP = 4,
  sym_segment_name = 5,
  anon_sym_TILDE = 6,
  anon_sym_CARET = 7,
  anon_sym_AMP = 8,
  aux_sym_number_token1 = 9,
  aux_sym_number_token2 = 10,
  aux_sym_float_token1 = 11,
  aux_sym_float_token2 = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_text = 15,
  sym_document = 16,
  sym_msh = 17,
  sym_segment = 18,
  sym_field = 19,
  sym_repeat = 20,
  sym_component = 21,
  sym_subcomponent = 22,
  sym_number = 23,
  sym_float = 24,
  sym_boolean = 25,
  aux_sym_document_repeat1 = 26,
  aux_sym_msh_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_document_token1] = "document_token1",
  [anon_sym_MSH] = "MSH",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET_TILDE_BSLASH_AMP] = "^~\\&",
  [sym_segment_name] = "segment_name",
  [anon_sym_TILDE] = "~",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym_msh] = "msh",
  [sym_segment] = "segment",
  [sym_field] = "field",
  [sym_repeat] = "repeat",
  [sym_component] = "component",
  [sym_subcomponent] = "subcomponent",
  [sym_number] = "number",
  [sym_float] = "float",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_msh_repeat1] = "msh_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_document_token1] = aux_sym_document_token1,
  [anon_sym_MSH] = anon_sym_MSH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET_TILDE_BSLASH_AMP] = anon_sym_CARET_TILDE_BSLASH_AMP,
  [sym_segment_name] = sym_segment_name,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym_msh] = sym_msh,
  [sym_segment] = sym_segment,
  [sym_field] = sym_field,
  [sym_repeat] = sym_repeat,
  [sym_component] = sym_component,
  [sym_subcomponent] = sym_subcomponent,
  [sym_number] = sym_number,
  [sym_float] = sym_float,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_msh_repeat1] = aux_sym_msh_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_MSH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET_TILDE_BSLASH_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_segment_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_msh] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_repeat] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_subcomponent] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_msh_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 12,
  [29] = 10,
  [30] = 15,
  [31] = 31,
  [32] = 25,
  [33] = 33,
  [34] = 16,
  [35] = 35,
  [36] = 18,
  [37] = 19,
  [38] = 20,
  [39] = 21,
  [40] = 22,
  [41] = 23,
  [42] = 24,
  [43] = 27,
  [44] = 44,
  [45] = 26,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '&', 33,
        '.', 17,
        '0', 35,
        'M', 6,
        '^', 31,
        'f', 9,
        't', 13,
        '|', 26,
        '~', 29,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == 'H') ADVANCE(25);
      END_STATE();
    case 4:
      if (lookahead == 'H') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == 'M') ADVANCE(7);
      if (lookahead == '^') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == 'S') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'S') ADVANCE(3);
      END_STATE();
    case 8:
      if (lookahead == '\\') ADVANCE(2);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 15:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == '~') ADVANCE(8);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(28);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(19);
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(24);
      if (lookahead == '|') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(21);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(22);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(20);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_document_token1);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '\r') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_MSH);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_CARET_TILDE_BSLASH_AMP);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_segment_name);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_TILDE);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_CARET);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '"', 54,
        '&', 34,
        '.', 63,
        '0', 37,
        '^', 32,
        'f', 56,
        't', 60,
        '~', 30,
        '\t', 49,
        0x0b, 49,
        '\f', 49,
        ' ', 49,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '"', 54,
        '&', 34,
        '.', 63,
        '0', 37,
        '^', 32,
        'f', 56,
        't', 60,
        '\t', 50,
        0x0b, 50,
        '\f', 50,
        ' ', 50,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '"', 54,
        '&', 34,
        '.', 63,
        '0', 37,
        'f', 56,
        't', 60,
        '\t', 51,
        0x0b, 51,
        '\f', 51,
        ' ', 51,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        '"', 54,
        '.', 63,
        '0', 37,
        'f', 56,
        't', 60,
        '\t', 52,
        0x0b, 52,
        '\f', 52,
        ' ', 52,
      );
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == '|') ADVANCE(1);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(1);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_text);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '|') ADVANCE(65);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 49},
  [3] = {.lex_state = 49},
  [4] = {.lex_state = 50},
  [5] = {.lex_state = 50},
  [6] = {.lex_state = 51},
  [7] = {.lex_state = 51},
  [8] = {.lex_state = 52},
  [9] = {.lex_state = 52},
  [10] = {.lex_state = 21},
  [11] = {.lex_state = 22},
  [12] = {.lex_state = 21},
  [13] = {.lex_state = 22},
  [14] = {.lex_state = 22},
  [15] = {.lex_state = 21},
  [16] = {.lex_state = 21},
  [17] = {.lex_state = 21},
  [18] = {.lex_state = 21},
  [19] = {.lex_state = 21},
  [20] = {.lex_state = 21},
  [21] = {.lex_state = 21},
  [22] = {.lex_state = 21},
  [23] = {.lex_state = 21},
  [24] = {.lex_state = 21},
  [25] = {.lex_state = 21},
  [26] = {.lex_state = 21},
  [27] = {.lex_state = 21},
  [28] = {.lex_state = 21},
  [29] = {.lex_state = 21},
  [30] = {.lex_state = 21},
  [31] = {.lex_state = 21},
  [32] = {.lex_state = 21},
  [33] = {.lex_state = 22},
  [34] = {.lex_state = 21},
  [35] = {.lex_state = 22},
  [36] = {.lex_state = 21},
  [37] = {.lex_state = 21},
  [38] = {.lex_state = 21},
  [39] = {.lex_state = 21},
  [40] = {.lex_state = 21},
  [41] = {.lex_state = 21},
  [42] = {.lex_state = 21},
  [43] = {.lex_state = 21},
  [44] = {.lex_state = 22},
  [45] = {.lex_state = 21},
  [46] = {.lex_state = 21},
  [47] = {.lex_state = 21},
  [48] = {.lex_state = 21},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_MSH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_segment_name] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(49),
    [sym_msh] = STATE(13),
    [anon_sym_MSH] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_field] = STATE(16),
    [sym_repeat] = STATE(22),
    [sym_component] = STATE(23),
    [sym_subcomponent] = STATE(24),
    [sym_number] = STATE(21),
    [sym_float] = STATE(21),
    [sym_boolean] = STATE(21),
    [anon_sym_TILDE] = ACTIONS(5),
    [anon_sym_CARET] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [aux_sym_number_token1] = ACTIONS(11),
    [aux_sym_number_token2] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_field] = STATE(34),
    [sym_repeat] = STATE(40),
    [sym_component] = STATE(41),
    [sym_subcomponent] = STATE(42),
    [sym_number] = STATE(39),
    [sym_float] = STATE(39),
    [sym_boolean] = STATE(39),
    [anon_sym_TILDE] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(23),
    [aux_sym_number_token1] = ACTIONS(25),
    [aux_sym_number_token2] = ACTIONS(25),
    [aux_sym_float_token1] = ACTIONS(27),
    [aux_sym_float_token2] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [sym_text] = ACTIONS(31),
  },
  [STATE(4)] = {
    [sym_repeat] = STATE(25),
    [sym_component] = STATE(23),
    [sym_subcomponent] = STATE(24),
    [sym_number] = STATE(21),
    [sym_float] = STATE(21),
    [sym_boolean] = STATE(21),
    [anon_sym_CARET] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [aux_sym_number_token1] = ACTIONS(11),
    [aux_sym_number_token2] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
  },
  [STATE(5)] = {
    [sym_repeat] = STATE(32),
    [sym_component] = STATE(41),
    [sym_subcomponent] = STATE(42),
    [sym_number] = STATE(39),
    [sym_float] = STATE(39),
    [sym_boolean] = STATE(39),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_AMP] = ACTIONS(23),
    [aux_sym_number_token1] = ACTIONS(25),
    [aux_sym_number_token2] = ACTIONS(25),
    [aux_sym_float_token1] = ACTIONS(27),
    [aux_sym_float_token2] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(29),
    [anon_sym_false] = ACTIONS(29),
    [sym_text] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_AMP,
    ACTIONS(17), 1,
      sym_text,
    STATE(24), 1,
      sym_subcomponent,
    STATE(26), 1,
      sym_component,
    ACTIONS(11), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 3,
      sym_number,
      sym_float,
      sym_boolean,
  [30] = 8,
    ACTIONS(23), 1,
      anon_sym_AMP,
    ACTIONS(31), 1,
      sym_text,
    STATE(42), 1,
      sym_subcomponent,
    STATE(45), 1,
      sym_component,
    ACTIONS(25), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(27), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 3,
      sym_number,
      sym_float,
      sym_boolean,
  [60] = 6,
    ACTIONS(17), 1,
      sym_text,
    STATE(27), 1,
      sym_subcomponent,
    ACTIONS(11), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(13), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(21), 3,
      sym_number,
      sym_float,
      sym_boolean,
  [84] = 6,
    ACTIONS(31), 1,
      sym_text,
    STATE(43), 1,
      sym_subcomponent,
    ACTIONS(25), 2,
      aux_sym_number_token1,
      aux_sym_number_token2,
    ACTIONS(27), 2,
      aux_sym_float_token1,
      aux_sym_float_token2,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(39), 3,
      sym_number,
      sym_float,
      sym_boolean,
  [108] = 3,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    STATE(15), 1,
      aux_sym_msh_repeat1,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [119] = 4,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      sym_segment_name,
    STATE(14), 1,
      aux_sym_document_repeat1,
    STATE(46), 1,
      sym_segment,
  [132] = 3,
    ACTIONS(35), 1,
      anon_sym_PIPE,
    STATE(10), 1,
      aux_sym_msh_repeat1,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [143] = 4,
    ACTIONS(39), 1,
      sym_segment_name,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      aux_sym_document_repeat1,
    STATE(47), 1,
      sym_segment,
  [156] = 4,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      sym_segment_name,
    STATE(14), 1,
      aux_sym_document_repeat1,
    STATE(48), 1,
      sym_segment,
  [169] = 3,
    ACTIONS(52), 1,
      anon_sym_PIPE,
    STATE(15), 1,
      aux_sym_msh_repeat1,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [180] = 2,
    ACTIONS(55), 1,
      anon_sym_PIPE,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [188] = 3,
    ACTIONS(57), 1,
      aux_sym_document_token1,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    STATE(31), 1,
      aux_sym_msh_repeat1,
  [198] = 2,
    ACTIONS(63), 1,
      anon_sym_PIPE,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [206] = 2,
    ACTIONS(67), 1,
      anon_sym_PIPE,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [214] = 2,
    ACTIONS(71), 1,
      anon_sym_PIPE,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [222] = 2,
    ACTIONS(75), 1,
      anon_sym_PIPE,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [230] = 2,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [238] = 2,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [246] = 2,
    ACTIONS(87), 1,
      anon_sym_PIPE,
    ACTIONS(85), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [254] = 2,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    ACTIONS(89), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [262] = 2,
    ACTIONS(95), 1,
      anon_sym_PIPE,
    ACTIONS(93), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [270] = 2,
    ACTIONS(99), 1,
      anon_sym_PIPE,
    ACTIONS(97), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [278] = 3,
    ACTIONS(41), 1,
      aux_sym_document_token1,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    STATE(29), 1,
      aux_sym_msh_repeat1,
  [288] = 3,
    ACTIONS(33), 1,
      aux_sym_document_token1,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    STATE(30), 1,
      aux_sym_msh_repeat1,
  [298] = 3,
    ACTIONS(50), 1,
      aux_sym_document_token1,
    ACTIONS(101), 1,
      anon_sym_PIPE,
    STATE(30), 1,
      aux_sym_msh_repeat1,
  [308] = 3,
    ACTIONS(59), 1,
      anon_sym_PIPE,
    ACTIONS(104), 1,
      aux_sym_document_token1,
    STATE(30), 1,
      aux_sym_msh_repeat1,
  [318] = 2,
    ACTIONS(89), 1,
      aux_sym_document_token1,
    ACTIONS(91), 1,
      anon_sym_PIPE,
  [325] = 1,
    ACTIONS(45), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [330] = 2,
    ACTIONS(50), 1,
      aux_sym_document_token1,
    ACTIONS(55), 1,
      anon_sym_PIPE,
  [337] = 1,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [342] = 2,
    ACTIONS(61), 1,
      aux_sym_document_token1,
    ACTIONS(63), 1,
      anon_sym_PIPE,
  [349] = 2,
    ACTIONS(65), 1,
      aux_sym_document_token1,
    ACTIONS(67), 1,
      anon_sym_PIPE,
  [356] = 2,
    ACTIONS(69), 1,
      aux_sym_document_token1,
    ACTIONS(71), 1,
      anon_sym_PIPE,
  [363] = 2,
    ACTIONS(73), 1,
      aux_sym_document_token1,
    ACTIONS(75), 1,
      anon_sym_PIPE,
  [370] = 2,
    ACTIONS(77), 1,
      aux_sym_document_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
  [377] = 2,
    ACTIONS(81), 1,
      aux_sym_document_token1,
    ACTIONS(83), 1,
      anon_sym_PIPE,
  [384] = 2,
    ACTIONS(85), 1,
      aux_sym_document_token1,
    ACTIONS(87), 1,
      anon_sym_PIPE,
  [391] = 2,
    ACTIONS(97), 1,
      aux_sym_document_token1,
    ACTIONS(99), 1,
      anon_sym_PIPE,
  [398] = 1,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_segment_name,
  [403] = 2,
    ACTIONS(93), 1,
      aux_sym_document_token1,
    ACTIONS(95), 1,
      anon_sym_PIPE,
  [410] = 2,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      aux_sym_document_token1,
  [417] = 2,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      aux_sym_document_token1,
  [424] = 1,
    ACTIONS(112), 1,
      aux_sym_document_token1,
  [428] = 1,
    ACTIONS(114), 1,
      ts_builtin_sym_end,
  [432] = 1,
    ACTIONS(116), 1,
      anon_sym_PIPE,
  [436] = 1,
    ACTIONS(118), 1,
      anon_sym_CARET_TILDE_BSLASH_AMP,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 30,
  [SMALL_STATE(8)] = 60,
  [SMALL_STATE(9)] = 84,
  [SMALL_STATE(10)] = 108,
  [SMALL_STATE(11)] = 119,
  [SMALL_STATE(12)] = 132,
  [SMALL_STATE(13)] = 143,
  [SMALL_STATE(14)] = 156,
  [SMALL_STATE(15)] = 169,
  [SMALL_STATE(16)] = 180,
  [SMALL_STATE(17)] = 188,
  [SMALL_STATE(18)] = 198,
  [SMALL_STATE(19)] = 206,
  [SMALL_STATE(20)] = 214,
  [SMALL_STATE(21)] = 222,
  [SMALL_STATE(22)] = 230,
  [SMALL_STATE(23)] = 238,
  [SMALL_STATE(24)] = 246,
  [SMALL_STATE(25)] = 254,
  [SMALL_STATE(26)] = 262,
  [SMALL_STATE(27)] = 270,
  [SMALL_STATE(28)] = 278,
  [SMALL_STATE(29)] = 288,
  [SMALL_STATE(30)] = 298,
  [SMALL_STATE(31)] = 308,
  [SMALL_STATE(32)] = 318,
  [SMALL_STATE(33)] = 325,
  [SMALL_STATE(34)] = 330,
  [SMALL_STATE(35)] = 337,
  [SMALL_STATE(36)] = 342,
  [SMALL_STATE(37)] = 349,
  [SMALL_STATE(38)] = 356,
  [SMALL_STATE(39)] = 363,
  [SMALL_STATE(40)] = 370,
  [SMALL_STATE(41)] = 377,
  [SMALL_STATE(42)] = 384,
  [SMALL_STATE(43)] = 391,
  [SMALL_STATE(44)] = 398,
  [SMALL_STATE(45)] = 403,
  [SMALL_STATE(46)] = 410,
  [SMALL_STATE(47)] = 417,
  [SMALL_STATE(48)] = 424,
  [SMALL_STATE(49)] = 428,
  [SMALL_STATE(50)] = 432,
  [SMALL_STATE(51)] = 436,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_msh_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_msh_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_msh_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subcomponent, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subcomponent, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repeat, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_repeat, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repeat, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_repeat, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_msh_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_msh, 5, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_msh, 4, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [114] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hl7(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hl7",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
